import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ components/navbar/Navbar";
import Modal from "./ components/modals/Modal";
import LoginModal from "./ components/modals/LoginModal";
import SignupModal from "./ components/modals/SignupModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Stayfinder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
    <p>helloo ohayo</p>
  )
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>

        <div className="pt-32">
          {children}
        </div>
        
        <LoginModal/>
        <SignupModal/>
      </body>
    </html>
  );
}
